### ISSUE TITLE
Create a new folder in the root directory called `.github`

### ISSUE THREAD

**Issue by theaderonkeadebisi** [teamNewDev/jobhunt#4]

**Comment by ebenezerdon** [comment]
@theaderonkeadebisi what's the purpose of this new issue you created?

**Comment by theaderonkeadebisi** [comment]
> 

I accidentally created a new issue, though I worked on the issue you assigned to me.
Can I know how it doesn’t follow the convention I worked on? I’m checking it out again.

**Comment by theaderonkeadebisi** [comment]
I edited the issue description because there was an error in the pull request I made before which I cancelled . The file was empty.
When I updated the file I made another pull request with a slightly different description.
