### ISSUE TITLE
Setup ESlint

### ISSUE THREAD

**Issue by ebenezerdon** [teamNewDev/jobhunt#5]
## Why This is Important?

Integrating ESLint into the project is crucial for maintaining code quality, ensuring consistency across the team, catching errors early, and enforcing JavaScript best practices. Its integration into the build process further ensures that only quality code gets deployed.

## Steps to Complete Task

1. [x] Ensure Node.js and npm are installed in the development environment.
2. [x] In the project root directory, initialize a `package.json` file by executing `npm init -y`.
3. [x] Install ESLint as a development dependency by executing `npm install eslint --save-dev`.
4. [x] Install the Airbnb JavaScript style guide configuration along with its peer dependencies.
5. [x] Create an `.eslintrc.json` file in the project root directory with the provided configuration:

```
{
  "root": true,
  "extends": "airbnb-base",
  "env": {
    "node": true,
    "es6": true,
    "mocha": true
  },
  "rules": {
    "one-var": 0,
    "one-var-declaration-per-line": 0,
    "new-cap": 0,
    "consistent-return": 0,
    "no-param-reassign": 0,
    "comma-dangle": 0,
    "curly": ["error", "multi-line"],
    "import/no-unresolved": [2, { "commonjs": true }],
    "no-shadow": ["error", { "allow": ["req", "res", "err"] }],
    "valid-jsdoc": ["error", {
      "requireReturn": true,
      "requireReturnType": true,
      "requireParamDescription": false,
      "requireReturnDescription": true
    }],
    "require-jsdoc": ["error", {
        "require": {
            "FunctionDeclaration": true,
            "MethodDefinition": true,
            "ClassDeclaration": true
        }
    }]
  }
}
```

6. [x] Add a lint script in the `package.json` file in the "scripts" section:
```json
"scripts": {
  "lint": "eslint ."
}
```

7. [x] Test ESLint by running `npm run lint`. ESLint should run and report any linting errors based on the rules set in the `.eslintrc.json` file.

**Dev Notes**

Remember that setting ESLint up this way allows linting to be done consistently across all developer environments, which is essential for maintaining a consistent coding style throughout the project.

Useful Links:
- [AirBnB Javascript](https://github.com/airbnb/javascript)
- [ESLint](https://www.npmjs.com/package/eslint)
- [ESLint Config AirBnB](https://www.npmjs.com/package/eslint-config-airbnb)
- [ESLint Plugin Import](https://www.npmjs.com/package/eslint-plugin-import)
- [Installing Node.js and npm](https://nodejs.org/)
- [npx install-peerdeps](https://www.npmjs.com/package/install-peerdeps)

**Comment by SageKyle** [comment]
@ebenezerdon  I have thoroughly followed all the steps, but when I run the command `npm run lint`, I get this error:
> Oops! Something went wrong! :(
>
> ESLint: 8.2.0
>
> No files matching the pattern "." were found.
Please check for typing mistakes in the pattern.

Could it be because the linting doesn't work for the files currently available in the project folder - the README, package.json, etc? i.e could the error be due to no supported file format, or from the `scripts` in `package.json`?

**Comment by ebenezerdon** [comment]
> @ebenezerdon I have thoroughly followed all the steps, but when I run the command `npm run lint`, I get this error:
> 
> > Oops! Something went wrong! :(
> > ESLint: 8.2.0
> > No files matching the pattern "." were found.
> > Please check for typing mistakes in the pattern.
> 
> Could it be because the linting doesn't work for the files currently available in the project folder - the README, package.json, etc? i.e could the error be due to no supported file format, or from the `scripts` in `package.json`?

@SageKyle add an `index.js` file with a Hello World `console.log()`
